[package]
name = "hamis"
version = "0.1.9"
edition = "2021"

[dependencies]
crossterm = { version = "0.29.0", default-features = false, features = [
    "windows",
] }
image = { version = "0.25.6", default-features = false, features = [
    "bmp",
    "ico",
    "jpeg",
    "png",
    "webp",
] }
